[package]
name = "core-ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = {workspace = true}
serde = {workspace = true} 
tokio = {workspace = true}
core-serde = {path = "../core-serde"}
core-shared = {path = "../core-shared"}