[package]
name = "core-dtos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bevy_ecs = {workspace = true}
serde = {workspace = true} 
wasm-bindgen = {workspace = true}
tsify = {workspace = true}

[target.'cfg(target_arch = "wasm32")'.dependencies]