[package]
name = "core-state"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
async-trait = {workspace = true}
core-shared = {path = "../core-shared"}
core-ecs = {path = "../core-ecs"}
core-dtos = {path = "../core-dtos"}